# Generated by Django 5.2 on 2025-05-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_createsuperuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
