# Generated by Django 5.2 on 2025-05-03 15:44

from django.db import migrations

from roles.models import RolePermission
from roles.services.permissions_config import PermissionsConfig


def init_permissions(*args):
    permissions_data = PermissionsConfig.get_permissions_meta()
    permissions = []
    for codename, permission_data in permissions_data.items():
        permissions.append(
            RolePermission(
                codename=codename,
                name=permission_data.name,
                description=permission_data.description,
                category=permission_data.category,
            )
        )
    RolePermission.objects.bulk_create(permissions, ignore_conflicts=True)


def reset_permissions(*args):
    permissions_data = PermissionsConfig.get_permissions_meta()
    for codename in permissions_data:
        RolePermission.objects.filter(codename=codename).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_role_is_everyone'),
    ]

    operations = [
        migrations.RunPython(init_permissions, reset_permissions),
    ]
